### ISSUE TITLE
ImportError: cannot import name create_eventloop

### ISSUE THREAD

**Issue by pinggit** [eonpatapon/contrail-api-cli#25]
after installation can't run it:
got these errors:
```
$ contrail-api-cli shell
Traceback (most recent call last):
  File "/home/pings/contrail-api-cli-venv/bin/contrail-api-cli", line 7, in <module>
    from contrail_api_cli.main import main
  File "/home/pings/contrail-api-cli-venv/local/lib/python2.7/site-packages/contrail_api_cli/main.py", line 12, in <module>
    from .manager import CommandManager
  File "/home/pings/contrail-api-cli-venv/local/lib/python2.7/site-packages/contrail_api_cli/manager.py", line 10, in <module>
    from .utils import Singleton
  File "/home/pings/contrail-api-cli-venv/local/lib/python2.7/site-packages/contrail_api_cli/utils.py", line 20, in <module>
    from prompt_toolkit.shortcuts import prompt, create_eventloop
ImportError: cannot import name create_eventloop
```

**Comment by eonpatapon** [comment]
I've uploaded a new version to pypi

Thanks for reporting the bug
