### ISSUE TITLE
DefaultStyle no longer available in prompt_toolkit.styles

### ISSUE THREAD

**Issue by Millnert** [eonpatapon/contrail-api-cli#7]
Traceback (most recent call last):
      File "/home/anticimex/Envs/contrail-api-cli/bin/contrail-api-cli", line 9, in <module>
        load_entry_point('contrail-api-cli==0.1b1', 'console_scripts', 'contrail-api-cli')()
      File "/home/anticimex/Envs/contrail-api-cli/local/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/home/anticimex/Envs/contrail-api-cli/local/lib/python2.7/site-packages/pkg_resources.py", line 2476, in load_entry_point
        return ep.load()
      File "/home/anticimex/Envs/contrail-api-cli/local/lib/python2.7/site-packages/pkg_resources.py", line 2190, in load
        ['__name__'])
      File "/home/anticimex/Envs/contrail-api-cli/local/lib/python2.7/site-packages/contrail_api_cli/main.py", line 11, in <module>
        from . import commands
      File "/home/anticimex/Envs/contrail-api-cli/local/lib/python2.7/site-packages/contrail_api_cli/commands.py", line 28, in <module>
        from .style import PromptStyle
      File "/home/anticimex/Envs/contrail-api-cli/local/lib/python2.7/site-packages/contrail_api_cli/style.py", line 3, in <module>
        from prompt_toolkit.styles import DefaultStyle
    ImportError: cannot import name DefaultStyle

Ref: 
https://github.com/jonathanslenders/python-prompt-toolkit/blob/422aad8e0f90f1e2b9009b7f4aa60cbc1ff0a407/CHANGELOG#L85

**Comment by Millnert** [comment]
Ahh, you have actually solved this by commit: https://github.com/eonpatapon/contrail-api-cli/commit/9fb26193a1070da78d0de86a36e09e7adff336a3

A new release perhaps? :)

**Comment by eonpatapon** [comment]
Yes I will make a new release, probably next week

**Comment by eonpatapon** [comment]
A new release has been upload to pypi (0.1b2)
